apiVersion: v2
name: cv
description: A Helm chart for CV Resume Application
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/sekretk/cv
sources:
  - https://github.com/sekretk/cv
maintainers:
  - name: sekretk
    email: ""
keywords:
  - resume
  - cv
  - portfolio
  - docker
