name: ReleaseTest
run-name: Test releases
on:
  push:
    branches: ['release-test']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: init
        run: git init

      - name: status
        run: git status 

      - name: tag
        run: |
          git tag TEST_TAG
          git push origin TEST_TAG

      # - uses: actions-ecosystem/action-push-tag@v1
      #   with:
      #     tag: TEST_TAG
      #     message: 'TEST_TAG'
          
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "2022-12-11T01:42:20"
      - name: Read version
        run: |
          VER=$(cat .version)
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Echo version
        run: echo version $VERSION

      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
